-- require("lspconfig").clangd.setup {
--     window = {
--         border = "rounded",
--         size = { height = "90%", width = "90%" },
--         scrolloff = nil,
--         sections = {
--             left = {
--                 size = "20%",
--                 border = nil, -- You can set border style for each section individually as well.
--             },
--             mid = {
--                 size = "40%",
--                 border = nil,
--             },
--             right = {
--                 -- No size option for right most section. It fills to
--                 -- remaining area.
--                 border = nil,
--                 preview = "leaf", -- Right section can show previews too.
--                 -- Options: "leaf", "always" or "never"
--             }
--         },
--     },
--     mappings = {
--         ["j"] = actions.next_sibling(),
--         ["k"] = actions.previous_sibling(),
--
--         ["h"] = actions.parent(),
--         ["l"] = actions.children(),
--         ["0"] = actions.root(),
--
--         ["v"] = actions.visual_name(),
--         ["V"] = actions.visual_scope(),
--
--         ["y"] = actions.yank_name(),
--         ["Y"] = actions.yank_scope(),
--
--         ["i"] = actions.insert_name(),
--         ["I"] = actions.insert_scope(),
--
--         ["a"] = actions.append_name(),
--         ["A"] = actions.append_scope(),
--
--         ["r"] = actions.rename(),
--
--         ["d"] = actions.delete(),
--
--         ["f"] = actions.fold_create(),
--         ["F"] = actions.fold_delete(),
--
--         ["c"] = actions.comment(),
--
--         ["<enter>"] = actions.select(),
--         ["o"] = actions.select(),
--
--         ["J"] = actions.move_down(),
--         ["K"] = actions.move_up(),
--
--         ["s"] = actions.toggle_preview(),
--
--         ["<C-v>"] = actions.vsplit(),
--         ["<C-h>"] = actions.hsplit(),
--
--         ["t"] = actions.telescope({
--             layout_config = {
--                 height = 0.60,
--                 width = 0.60,
--                 prompt_position = "top",
--                 preview_width = 0.50
--             },
--             layout_strategy = "horizontal"
--         }),
--
--         ["g?"] = actions.help(),
--     },
-- }

vim.keymap.set('n', '<leader>nv', ':Navbuddy<CR>')
